services:
  db:
    image: postgres:17
    container_name: blip-postgres
    environment:
      POSTGRES_USER: blip_user
      POSTGRES_PASSWORD: blip_password
      POSTGRES_DB: blip_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
volumes:
  postgres_data:
